import type { WeddingEvent, Venue, DressCodeColor, StoryStep } from '@/types'

export const WEDDING = {
  groomFirstName: 'Elvis',
  groomLastName:  'Dirane',
  brideFirstName: 'Ange Esther',
  brideLastName:  '',
  coupleNames:    'Ange Esther & Elvis Dirane',
  theme:          'Le Ciel Ouvert',
  bibleVerse:     '« La femme n\'est pas sans l\'homme, ni l\'homme sans la femme, dans le Seigneur. »',
  bibleRef:       '1 Corinthiens 11:11',

  dates: {
    wedding:      new Date('2026-05-16T10:00:00'),
    civil:        new Date('2026-05-14T09:00:00'),
    rsvpDeadline: '1er Mai 2026',
  },

  events: [
    {
      id:          'civil',
      date:        '14 Mai 2026',
      day:         'Jeudi',
      title:       'Mariage Civil',
      time:        'À préciser',
      location:    'Mairie de Mewoulou',
      address:     'Mewoulou, Yaoundé',
      mapsUrl:     'https://maps.google.com/?q=Mewoulou+Yaounde',
      icon:        '⚖️',
      description: 'Union civile devant les autorités',
    },
    {
      id:          'religious',
      date:        '16 Mai 2026',
      day:         'Samedi',
      title:       'Cérémonie Religieuse',
      time:        'À préciser',
      location:    'EEC Melen',
      address:     'Melen, Yaoundé',
      mapsUrl:     'https://maps.google.com/?q=EEC+Melen+Yaounde',
      icon:        '✝️',
      description: 'Célébration de l\'union devant Dieu',
    },
    {
      id:          'reception',
      date:        '16 Mai 2026',
      day:         'Samedi',
      title:       'Réception & Festivités',
      time:        'À préciser',
      location:    'Helen Hôtel',
      address:     'Nsam-Efoulan, Yaoundé',
      mapsUrl:     'https://maps.google.com/?q=Helen+Hotel+Yaounde',
      icon:        '🥂',
      description: 'Dîner, danse et célébration',
    },
  ] as WeddingEvent[],

  venues: [
    {
      name:    'Maison familiale Mewoulou',
      role:    'Mariage Civil — 14 Mai',
      address: 'Mewoulou, Yaoundé, Cameroun',
      mapsUrl: 'https://maps.google.com/?q=Mewoulou+Yaounde',
    },
    {
      name:    'Nsam-Efoulan',
      role:    'Rassemblement familial',
      address: 'Nsam-Efoulan, Yaoundé, Cameroun',
      mapsUrl: 'https://maps.google.com/?q=Nsam+Efoulan+Yaounde',
    },
    {
      name:    'EEC Melen',
      role:    'Cérémonie Religieuse — 16 Mai',
      address: 'Melen, Yaoundé, Cameroun',
      mapsUrl: 'https://maps.google.com/?q=EEC+Melen+Yaounde',
    },
    {
      name:    'Helen Hôtel',
      role:    'Réception — 16 Mai',
      address: 'Yaoundé, Cameroun',
      mapsUrl: 'https://maps.google.com/?q=Helen+Hotel+Yaounde',
    },
  ] as Venue[],

  dressCode: {
    title:       'Dress Code',
    subtitle:    'Élégance & Grâce',
    description: 'Pour honorer ce jour béni, nous vous invitons à revêtir l\'élégance. Adoptez des tenues dans les tons de la cérémonie : bleu ciel, or, crème et blanc. Votre présence illuminera notre journée.',
    note:        'Évitez le noir et le rouge vif, réservés à d\'autres occasions.',
    colors: [
      { name: 'Bleu Ciel', hex: '#74BCFF', label: 'Principal' },
      { name: 'Or Doré',   hex: '#8a6a08', label: 'Accent' },
      { name: 'Crème',     hex: '#F9F4EC', label: 'Secondaire' },
      { name: 'Blanc Pur', hex: '#FEFEFE', label: 'Classique' },
    ] as DressCodeColor[],
  },

  story: [
    {
      id:          1,
      year:        '2020',
      title:       'La Première Rencontre',
      description: 'Tout a commencé par un regard, un sourire, et la certitude que Dieu avait quelque chose de spécial en réserve. Leur rencontre a été le début d\'une belle aventure bénie par le Seigneur.',
      imageSrc:    '/images/couple/Images mariage/ED--5.JPG',
      imageAlt:    'Première rencontre d\'Ange Esther et Elvis',
    },
    {
      id:          2,
      year:        '2021',
      title:       'Les Premiers Pas',
      description: 'Entre promenades et longues conversations, leur complicité grandissait de jour en jour. Ils découvraient ensemble leurs rêves communs et leur foi partagée en Dieu.',
      imageSrc:    '/images/couple/Images mariage/ED--17.JPG',
      imageAlt:    'Premiers moments ensemble',
    },
    {
      id:          3,
      year:        '2023',
      title:       'La Promesse',
      description: 'Un jour béni, Elvis a pris la main d\'Ange Esther et lui a promis son amour pour la vie. Les fiançailles ont scellé devant Dieu et leurs proches une union déjà écrite au ciel.',
      imageSrc:    '/images/couple/Images mariage/ED--16.JPG',
      imageAlt:    'Les fiançailles',
    },
    {
      id:          4,
      year:        '2026',
      title:       'Le Ciel Ouvert',
      description: 'Le 16 Mai 2026, sous un ciel ouvert, ils uniront leurs vies devant Dieu, leurs familles et leurs amis. Une nouvelle page commence, écrite ensemble, pour toujours.',
      imageSrc:    '/images/couple/Images mariage/ED--18.JPG',
      imageAlt:    'Le grand jour approche',
    },
  ] as StoryStep[],

  /* 18 photos — images réelles du couple */
  gallery: [
    { src: '/images/couple/Images mariage/ED--5.JPG',  alt: 'Ange Esther & Elvis — portrait' },
    { src: '/images/couple/Images mariage/ED--6.JPG',  alt: 'Moment de complicité' },
    { src: '/images/couple/Images mariage/ED--7.JPG',  alt: 'Séance photo couple' },
    { src: '/images/couple/Images mariage/ED--8.JPG',  alt: 'Regard amoureux' },
    { src: '/images/couple/Images mariage/ED--9.JPG',  alt: 'Promenade en nature' },
    { src: '/images/couple/Images mariage/ED--10.JPG', alt: 'Éclats de rire' },
    { src: '/images/couple/Images mariage/ED--11.JPG', alt: 'Moment de tendresse' },
    { src: '/images/couple/Images mariage/ED--12.JPG', alt: 'Les fiançailles' },
    { src: '/images/couple/Images mariage/ED--13.JPG', alt: 'Portrait romantique' },
    { src: '/images/couple/Images mariage/ED--14.JPG', alt: 'Coucher de soleil' },
    { src: '/images/couple/Images mariage/ED--15.JPG', alt: 'Séance en ville' },
    { src: '/images/couple/Images mariage/ED--16.JPG', alt: 'Complicité naturelle' },
    { src: '/images/couple/Images mariage/ED--17.JPG', alt: 'Lumière dorée' },
    { src: '/images/couple/Images mariage/ED--18.JPG', alt: 'Souvenir précieux' },
    { src: '/images/couple/Images mariage/ED--19.JPG', alt: 'Instant de joie' },
    { src: '/images/couple/Images mariage/ED--3.JPG',  alt: 'Regard complice' },
    { src: '/images/couple/Images mariage/ED--4.JPG',  alt: 'Portrait en nature' },
    { src: '/images/couple/Images mariage/ED--5.JPG',  alt: 'Notre histoire' },
  ],
} as const